FROM pytorch/pytorch:0.4_cuda9_cudnn7
#FROM pytorch/pytorch:0.4
# add package for progress indicator
RUN pip install tqdm pyarrow
RUN pip install tensorboardX
RUN pip install --upgrade pip
RUN pip install sklearn
